### ISSUE TITLE
悬浮窗可以显示DPS吗

### ISSUE THREAD

**Issue by thebluedarker** [Tanimodori/GBFR-ACT-Frontend#2]
在样式里加dps、DPS都不能增加对应的列，是我关键字加得不对还是就没有相关的功能啊

**Comment by Tanimodori** [comment]
一分钟内DPS窗口对应的列名是`damageInMinutePerSecond`，后续版本将对其进行更为人性化的UI改进，对此造成的不便深表歉意。

**Comment by thebluedarker** [comment]
其实我想看的是全局的DPS，理论上来说这个也能看吧，猜了一下totalDamagePerSecond和DamagePerSecond与damagePerSecond都没猜对。一分钟内伤害倒是猜对了damageInMinute

**Comment by Tanimodori** [comment]
理论上可以统计出全局DPS，将在下一个版本更新相关功能。

**Comment by Tanimodori** [comment]
Fixed in 8687fc822cceb7d6a9bc769dd1afea8079d3a48e

**Comment by Tanimodori** [comment]
现在可以用`totalDamagePerSecond`来展示全局的DPS。
